version: "3.3"

services:
    db:
        image: mariadb:10.6
        volumes:
            - data-mysql:/var/lib/mysql
            - ./initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=password
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
            timeout: 20s
            retries: 10

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=db:3306

    registry:
        depends_on:
            - db
        image: dronedb/registry
        volumes:
            - ./data/App_Data:/Registry/App_Data
            - ./appsettings-testing.json:/Registry/appsettings.json
            - ./data/logs:/Registry/logs
        ports:
            - "5000:5000"
        restart: unless-stopped

volumes:
  data-mysql:
    driver: local