name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: registry
    - uses: actions/checkout@v2
      with:
        repository: DroneDB/DroneDB
        submodules: "recursive"
        path: ddb
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
    - name: setup utils
      run: sudo apt-get update && sudo apt-get install -y spatialite-bin libsqlite3-mod-spatialite
    - name: Build C++ lib
      run: |
          cd ddb
          scripts/ubuntu_deps.sh
          mkdir -p build
          cd build
          cmake -DBUILD_TESTING=OFF ..
          make -j$(nproc) ddb
          sudo make -j$(nproc) install
          sudo ldconfig          
    - name: Install dependencies
      run: |
        cd registry
        export PATH="$HOME/ddb/build:$PATH"
        dotnet test -c Release --verbosity minimal
